apiVersion: apps/v1
kind: Deployment
metadata:
  name: workertests-cron
spec:
  selector:
    matchLabels:
      app: workertests-cron
  replicas: 3
  template:
    metadata:
      labels:
        app: workertests-cron
    spec:
      containers:
        - name: workertests-cron
          image: renatogroffe/workertests-dotnet8:2